#!/bin/bash
tgcli_version="171008-nightly"
luarocks_version=2.4.2
lualibs=(
'luasec'
'luarepl'
'lbase64 20120807-3'
'luafilesystem'
'lub'
'luaexpat'
'redis-lua'
'lua-cjson'
'fakeredis'
'xml'
'feedparser'
'serpent'
)

today=`date +%F`
install() {
sudo apt-get update 
chmod +x bot
chmod +x tg
chmod +x Company
}
get_sub() {
local flag=false c count cr=$'\r' nl=$'\n'
while IFS='' read -d '' -rn 1 c; do
 if $flag; then
 printf '%c' "$c"
  else
if [[ $c != $cr && $c != $nl ]]; then
  count=0
 else
((count++))
 if ((count > 1)); then
flag=true
fi
fi
fi
 done
}
make_progress() {
exe=`lua <<-EOF
    print(tonumber($1)/tonumber($2)*100)
EOF
`
    echo ${exe:0:4}
}
 get_tgcli_version() {
	echo "$tgcli_version"
}
 download_libs_lua() {
    if [[ ! -d "logs" ]]; then mkdir logs; fi
    if [[ -f "logs/logluarocks_${today}.txt" ]]; then rm logs/logluarocks_${today}.txt; fi
    local i
    for ((i=0;i<${#lualibs[@]};i++)); do
        printf "\r\33[2K"
        printf "\r• Installing Luarocks: wait... [`make_progress $(($i+1)) ${#lualibs[@]}`%%] [$(($i+1))/${#lualibs[@]}] ${lualibs[$i]}"
        ./.luarocks/bin/luarocks install ${lualibs[$i]} &>> logs/logluarocks_${today}.txt
    done
    sleep 0.2
sleep 0.2
printf "\n• Logfile created: $PWD/logs/logluarocks_${today}.txt\nDone\n"
rm -rf luarocks-2.2.2*
}
startbotlogo() {
sleep 0.5
clear
f=3 b=4
for j in f b; do
for i in {0..7}; do
printf -v $j$i %b "\e[${!j}${i}m"
done
done
echo -e "                \e[100m                                Bot Running                                \e[00;37;40m"
echo  "                             BOT STARTED.                 "
echo ""
}
 config() {
mkdir $HOME/.telegram-bot; cat <<EOF > $HOME/.telegram-bot/config
default_profile = "main";
main = {
lua_script = "$HOME/bot/bot/bot.lua";
};
EOF
printf "\nDone\n"
}
launch() {
./tg | grep -v "{"
}
resetlogin() {
 rm -rf $HOME/.telegram-bot
}
Bot(){
mkdir $HOME/.telegram-bot; cat <<EOF > $HOME/.telegram-bot/config
default_profile = "main";
main = {
lua_script = "$HOME/bot/bot/bot.lua";
};
EOF
printf "\nDone\n"
}
loginCli() {
./tg -p main --login --phone=${1}
} 
loginApi() {
./tg -p main --login --bot=${1}
}
function gitpull() {
git checkout C  bot/ libs/
git pull
echo chmod +x C | /bin/bash
version=$(echo "./C tgcli_version" | /bin/bash)
updateTD $version
}
updateTD() {
wget --progress=bar:force https://valtman.name/files/telegram-bot-${1}-linux 2>&1 | get_sub
mv telegram-bot-${1}-linux tg; chmod +x tg
}
CONFIG() {
TXT=(
""
)
printf "${TXT}"
printf "\n"
}
warning() {
TXT=(
""
)
printf "${TXT}"
printf "\n"
}
case $1 in
config)
CONFIG
config ${2}
exit ;;
login)
echo "Send Your Bot Number ..."
read phone_number
loginCli ${phone_number}
echo 'Done.'
exit;;
Change-Number)
echo 'please wait...'
sleep 1
resetlogin
Bot
echo 'Done.'
exit;;
install)
install
exit;;
run)
startbotlogo
launch
exit;;
update)
gitpull
updateTD
exit ;;
tgcli_version)
get_tgcli_version
exit ;;
help)
echo ""
exit ;;
esac
warning
exit 0
 
